build:
    image: kradalby/ci-tox:latest
    pull: true
    commands:
      - echo "Deploying"

#notify:
#  email:
#    from: drone@fap.no
#    host: smtp.stud.ntnu.no
#    port: 25
#    recipients:
#      - kradalby@kradalby.no

deploy:
  ssh:
    host: seel.fap.no
    user: www
    port: 22
    when:
        branch: master
    commands:
      - cd /usr/local/www/kradalby.no/presentations
      - git pull
      - git submodule update --recursive
      - git submodule foreach git pull origin master
      - echo "done"
