---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: build
  cache: true
  pull: if-not-exists
  image: plugins/docker
  settings:
    repo: kradalby/presentations
    tags:
    - ${DRONE_COMMIT_SHA:0:8}
    - latest
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

- name: deploy
  pull: if-not-exists
  image: quay.io/honestbee/drone-kubernetes
  settings:
    container: presentations-container
    deployment: presentations-deployment
    namespace: presentations
    repo: kradalby/presentations
    tag:
    - ${DRONE_COMMIT_SHA:0:8}
  environment:
    KUBERNETES_CERT:
      from_secret: kubernetes_cert
    KUBERNETES_SERVER:
      from_secret: kubernetes_server
    KUBERNETES_TOKEN:
      from_secret: kubernetes_token

- name: notify
  pull: if-not-exists
  image: drillster/drone-email
  settings:
    from: drone@drone.fap.no
    host: smtp.fap.no
    port: 25
    recipients:
    - kradalby@kradalby.no
    skip_verify: true
  when:
    status:
    - success
    - changed
    - failure
