build:
    image: kradalby/ci-tox:latest
    pull: true
    commands:
      - echo "Deploying"

notify:
  email:
    from: drone@fap.no
    host: mail.ntnu.fap.no
    port: 25
    recipients:
      - kradalby@kradalby.no
    when:
        branch: master

deploy:
  ssh:
    host: seel.terra.fap.no
    user: www
    port: 22
    when:
        branch: master
    commands:
      - cd /usr/local/www/presentations.kradalby.no/
      - git pull
      - git submodule update --recursive
      - git submodule foreach git pull origin master
      - echo "done"
