pipeline:
  build:
    image: kradalby/ci-tox:latest
    pull: true
    commands:
      - echo "Deploying"

  ssh:
    image: appleboy/drone-ssh
    host:
     - seel.terra.fap.no
    user: www
    port: 22
    script:
        - cd /usr/local/www/presentations.kradalby.no/
        - git pull
        - git submodule update --recursive
        - git submodule foreach git pull origin master
        - echo "done"
    when:
        status: success
        branch: master

  notify:
    image: drillster/drone-email
    host: mail.ntnu.fap.no
    port: 25
    from: drone@drone.fap.no
    recipients: [ kradalby@kradalby.no ]
    when:
      status: [ success, changed, failure ]
